Fix TypeError: %X format: an integer is required, not float
When random colour is turned off and an object is drawn,

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Physics.activity/activity.py", line 234, in __random_toggled_cb
    self._random_off(random)
  File "/usr/share/sugar/activities/Physics.activity/activity.py", line 256, in _random_off
    random.get_icon_widget().set_stroke_color(self._rgb8x(color))
  File "/usr/share/sugar/activities/Physics.activity/activity.py", line 275, in _rgb8x
    return '#%.2X%.2X%.2X' % self._rgb8(color)
TypeError: %X format: an integer is required, not float
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Physics.activity/activity.py", line 266, in __timeout_cb
    random.get_icon_widget().set_stroke_color('#%.2X%.2X%.2X' % color)
TypeError: %X format: an integer is required, not float

Signed-off-by: James Cameron <quozl@laptop.org>