Fix XML parse error
On Ubuntu 20.04 with librsvg 2.48.0 the activity logs contain;

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sugar3/graphics/icon.py", line 140, in load
    return Rsvg.Handle.new_from_data(icon.encode('utf-8'))
gi.repository.GLib.Error: rsvg-error-quark: XML parse error: error code=201 (3) in (null):22:40: Namespace prefix inkscape for connector-curvature on path is not defined (0)

librsvg 2.47.0 introduced stricter namespaces in the XML parser,
https://gitlab.gnome.org/GNOME/librsvg/-/blob/master/NEWS#L67

so add namespace declarations.