Fix traceback during sharing
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/home/olpc/Activities/Physics.activity/collabwrapper.py", line 798, in _received_cb
    self._activity_cb(buddy, msg)
  File "/home/olpc/Activities/Physics.activity/collabwrapper.py", line 294, in __received_cb
    data = self.activity.get_data()
TypeError: GObject.get_data() takes exactly 1 argument (0 given)

Caused by missing method.